[build-system]
requires = [
    "setuptools>=84.0.0",
    "wheel>=0.48.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "titulum"
version = "1.0.2"
description = ""
requires-python = ">=3.12"
authors = [
    { name = "Helmut Konrad Schewe", email = "helmutus@outlook.com" },
]
dependencies = [
    "utilo>=2.110.2,<3.0.0",
    "iamraw>= 4.95.0,< 5.0.0",
    "elementae>=1.0.1,<2.0.0",
    "germania>=1.32.2,<2.0.0",
    "scipy>=1.18.1,<2.0.0",
]
keywords = []
classifiers = [
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "MIT"
license-files = [
    "LICENSE",
]

[project.readme]
file = "README"
content-type = "text/markdown"

[project.optional-dependencies]
dev = [
    "utilotest>=1.1.1,<2.0.0",
    "gennex>=1.1.0,<2.0.0",
    "groupmes>=1.1.0,<2.0.0",
    "hoverpower>=1.7.0,<3.0.0",
    "capita>=1.25.3,<2.0.0",
    "rawmaker>=2.40.5,<3.0.0",
    "layouta>=1.1.0,<2.0.0",
    "pagenumber>=1.0.0,<2.0.0",
]

[project.urls]
Homepage = "https://github.com/anaticulae/titulum"
Repository = "https://github.com/anaticulae/titulum"

[project.scripts]
headlines = "titulum.cli:main"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]

[tool.semantic_release.changelog]
mode = "init"
output_format = "md"

[tool.semantic_release.changelog.default_templates]
changelog_file = "CHANGELOG"

[tool.semantic_release.commit_parser_options]
patch_tags = [
    "build",
    "chore",
    "ci",
    "deps",
    "docs",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
minor_tags = [
    "feat",
]

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "titulum",
    "titulum.cluster",
    "titulum.feature",
    "titulum.improve",
    "titulum.levelfour",
    "titulum.multiline",
    "titulum.nlarge",
    "titulum.nolevel",
    "titulum.single",
    "titulum.standard",
]
exclude = [
    "tests*",
]

[tool.hoverpower]
packages = [
    "MASTER",
    "BACHELOR",
    "DOCU",
]
